# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-07 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='question_answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(default=0)),
                ('choicename', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choicename', to='app_question.question_choices')),
                ('questionname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionname', to='app_question.app_question')),
            ],
            options={
                'verbose_name_plural': 'Question-Asnswer',
            },
        ),
    ]
